#docker-compose -f docker-compose-dev.yml up -d
version: '3.7'

services:
  custom:
    image: node:16-alpine3.14
    container_name: custom
    environment:
      CONFIG_REDIS_URI: redis://:${REDIS_PASS}@localhost:6379
      PORT: 8002
    working_dir: /app
    volumes:
      - $HOME/uzrnem/redis:/app
    network_mode: host
    entrypoint: tail -f /dev/null